[tool]
id = "dev.tyler.sudoku"
label = "Sudoku"
versionCode = 4
versionName = "1.3"
permissions = []
# change if you run this on an LP3!
# serverPackage = "com.lightos"
serverPackage = "com.thelightphone.sdk.emulator"
