package com.thelightphone.sdk.ui

import androidx.annotation.DrawableRes

/** Generated from LightOS/assets/icon. Do not edit by hand. */
internal object LightIconAssets {
    @DrawableRes
    fun resolve(assetKey: String): Int? = when (assetKey) {
        "AcceptBlack" -> R.drawable.ic_accept_black
        "AcceptWhite" -> R.drawable.ic_accept_white
        "AddBlack" -> R.drawable.ic_add_black
        "AddWhite" -> R.drawable.ic_add_white
        "AirplaneBlack" -> R.drawable.ic_airplane_black
        "AirplaneWhite" -> R.drawable.ic_airplane_white
        "AlarmBlack" -> R.drawable.ic_alarm_black
        "AlarmWhite" -> R.drawable.ic_alarm_white
        "ArrowDownBlack" -> R.drawable.ic_arrow_down_black
        "ArrowDownWhite" -> R.drawable.ic_arrow_down_white
        "ArrowRightBlack" -> R.drawable.ic_arrow_right_black
        "ArrowRightWhite" -> R.drawable.ic_arrow_right_white
        "AudioMessageBlack" -> R.drawable.ic_audio_message_black
        "AudioMessageWhite" -> R.drawable.ic_audio_message_white
        "BackBlack" -> R.drawable.ic_back_black
        "BackWhite" -> R.drawable.ic_back_white
        "BatteryAlmostFullBlack" -> R.drawable.ic_battery_almost_full_black
        "BatteryAlmostFullWhite" -> R.drawable.ic_battery_almost_full_white
        "BatteryChargingBlack" -> R.drawable.ic_battery_charging_black
        "BatteryChargingWhite" -> R.drawable.ic_battery_charging_white
        "BatteryEmptyBlack" -> R.drawable.ic_battery_empty_black
        "BatteryEmptyWhite" -> R.drawable.ic_battery_empty_white
        "BatteryErrorBlack" -> R.drawable.ic_battery_error_black
        "BatteryErrorWhite" -> R.drawable.ic_battery_error_white
        "BatteryFullBlack" -> R.drawable.ic_battery_full_black
        "BatteryFullWhite" -> R.drawable.ic_battery_full_white
        "BatteryHalfBlack" -> R.drawable.ic_battery_half_black
        "BatteryHalfWhite" -> R.drawable.ic_battery_half_white
        "BatteryOneQuarterBlack" -> R.drawable.ic_battery_one_quarter_black
        "BatteryOneQuarterWhite" -> R.drawable.ic_battery_one_quarter_white
        "BatteryThreeQuartersBlack" -> R.drawable.ic_battery_three_quarters_black
        "BatteryThreeQuartersWhite" -> R.drawable.ic_battery_three_quarters_white
        "BluetoothBlack" -> R.drawable.ic_bluetooth_black
        "BluetoothWhite" -> R.drawable.ic_bluetooth_white
        "CallBlack" -> R.drawable.ic_call_black
        "CallWhite" -> R.drawable.ic_call_white
        "Camera" -> R.drawable.ic_camera
        "CameraBrightness" -> R.drawable.ic_camera_brightness
        "CameraFlashAuto" -> R.drawable.ic_camera_flash_auto
        "CameraFlashOff" -> R.drawable.ic_camera_flash_off
        "CameraFlashOn" -> R.drawable.ic_camera_flash_on
        "CameraFocusLocked" -> R.drawable.ic_camera_focus_locked
        "CameraFocusLocking" -> R.drawable.ic_camera_focus_locking
        "CameraLandscape" -> R.drawable.ic_camera_landscape
        "CameraRecording" -> R.drawable.ic_camera_recording
        "CameraSettings" -> R.drawable.ic_camera_settings
        "CeMarkBlack" -> R.drawable.ic_ce_mark_black
        "CeMarkWhite" -> R.drawable.ic_ce_mark_white
        "CircleBlack" -> R.drawable.ic_circle_black
        "CircleWhite" -> R.drawable.ic_circle_white
        "CloseBlack" -> R.drawable.ic_close_black
        "CloseWhite" -> R.drawable.ic_close_white
        "ComposeBlack" -> R.drawable.ic_compose_black
        "ComposeWhite" -> R.drawable.ic_compose_white
        "ContactsBlack" -> R.drawable.ic_contacts_black
        "ContactsWhite" -> R.drawable.ic_contacts_white
        "CrosshairBlack" -> R.drawable.ic_crosshair_black
        "CrosshairWhite" -> R.drawable.ic_crosshair_white
        "DeleteBlack" -> R.drawable.ic_delete_black
        "DeleteWhite" -> R.drawable.ic_delete_white
        "DenyBlack" -> R.drawable.ic_deny_black
        "DenyWhite" -> R.drawable.ic_deny_white
        "DialpadBlack" -> R.drawable.ic_dialpad_black
        "DialpadWhite" -> R.drawable.ic_dialpad_white
        "DirectionsArrivalBlack" -> R.drawable.ic_directions_arrival_black
        "DirectionsArrivalWhite" -> R.drawable.ic_directions_arrival_white
        "DirectionsBusBlack" -> R.drawable.ic_directions_bus_black
        "DirectionsBusWhite" -> R.drawable.ic_directions_bus_white
        "DirectionsFerryBlack" -> R.drawable.ic_directions_ferry_black
        "DirectionsFerryWhite" -> R.drawable.ic_directions_ferry_white
        "DirectionsLeftBlack" -> R.drawable.ic_directions_left_black
        "DirectionsLeftWhite" -> R.drawable.ic_directions_left_white
        "DirectionsMiddleForkBlack" -> R.drawable.ic_directions_middle_fork_black
        "DirectionsMiddleForkWhite" -> R.drawable.ic_directions_middle_fork_white
        "DirectionsPedestrianBlack" -> R.drawable.ic_directions_pedestrian_black
        "DirectionsPedestrianWhite" -> R.drawable.ic_directions_pedestrian_white
        "DirectionsRightBlack" -> R.drawable.ic_directions_right_black
        "DirectionsRightWhite" -> R.drawable.ic_directions_right_white
        "DirectionsRoundAboutBlack" -> R.drawable.ic_directions_round_about_black
        "DirectionsRoundAboutWhite" -> R.drawable.ic_directions_round_about_white
        "DirectionsSlightLeftBlack" -> R.drawable.ic_directions_slight_left_black
        "DirectionsSlightLeftWhite" -> R.drawable.ic_directions_slight_left_white
        "DirectionsSlightRightBlack" -> R.drawable.ic_directions_slight_right_black
        "DirectionsSlightRightWhite" -> R.drawable.ic_directions_slight_right_white
        "DirectionsStraightBlack" -> R.drawable.ic_directions_straight_black
        "DirectionsStraightWhite" -> R.drawable.ic_directions_straight_white
        "DirectionsSubwayBlack" -> R.drawable.ic_directions_subway_black
        "DirectionsSubwayWhite" -> R.drawable.ic_directions_subway_white
        "DirectionsTrainBlack" -> R.drawable.ic_directions_train_black
        "DirectionsTrainWhite" -> R.drawable.ic_directions_train_white
        "DirectionsUTurnLeftBlack" -> R.drawable.ic_directions_uturn_left_black
        "DirectionsUTurnLeftWhite" -> R.drawable.ic_directions_uturn_left_white
        "DirectionsUTurnRightBlack" -> R.drawable.ic_directions_uturn_right_black
        "DirectionsUTurnRightWhite" -> R.drawable.ic_directions_uturn_right_white
        "DownBlack" -> R.drawable.ic_down_black
        "DownWhite" -> R.drawable.ic_down_white
        "DownloadArrowBlack" -> R.drawable.ic_download_arrow_black
        "DownloadArrowWhite" -> R.drawable.ic_download_arrow_white
        "DownloadedArrowBlack" -> R.drawable.ic_downloaded_arrow_black
        "DownloadedArrowWhite" -> R.drawable.ic_downloaded_arrow_white
        "EllipseBlack" -> R.drawable.ic_ellipse_black
        "EllipseWhite" -> R.drawable.ic_ellipse_white
        "EmergencyBlack" -> R.drawable.ic_emergency_black
        "EmergencyWhite" -> R.drawable.ic_emergency_white
        "FastForwardBlack" -> R.drawable.ic_fast_forward_black
        "FastForwardWhite" -> R.drawable.ic_fast_forward_white
        "FccMarkBlack" -> R.drawable.ic_fcc_mark_black
        "FccMarkWhite" -> R.drawable.ic_fcc_mark_white
        "LargeListBlack" -> R.drawable.ic_large_list_black
        "LargeListWhite" -> R.drawable.ic_large_list_white
        "LightLogoBlack" -> R.drawable.ic_light_logo_black
        "LightLogoWhite" -> R.drawable.ic_light_logo_white
        "ListBlack" -> R.drawable.ic_list_black
        "ListWhite" -> R.drawable.ic_list_white
        "LoopBlack" -> R.drawable.ic_loop_black
        "LoopWhite" -> R.drawable.ic_loop_white
        "MapBlack" -> R.drawable.ic_map_black
        "MapWhite" -> R.drawable.ic_map_white
        "MediaBlack" -> R.drawable.ic_media_black
        "MediaWhite" -> R.drawable.ic_media_white
        "MicrophoneBlack" -> R.drawable.ic_microphone_black
        "MicrophoneWhite" -> R.drawable.ic_microphone_white
        "MissedCallBlack" -> R.drawable.ic_missed_call_black
        "MissedCallWhite" -> R.drawable.ic_missed_call_white
        "MuteBlack" -> R.drawable.ic_mute_black
        "MuteWhite" -> R.drawable.ic_mute_white
        "PauseBlack" -> R.drawable.ic_pause_black
        "PauseWhite" -> R.drawable.ic_pause_white
        "PencilBlack" -> R.drawable.ic_pencil_black
        "PencilWhite" -> R.drawable.ic_pencil_white
        "PlayBlack" -> R.drawable.ic_play_black
        "PlayWhite" -> R.drawable.ic_play_white
        "RefreshBlack" -> R.drawable.ic_refresh_black
        "RefreshWhite" -> R.drawable.ic_refresh_white
        "ReverseOrderBlack" -> R.drawable.ic_reverse_order_black
        "ReverseOrderWhite" -> R.drawable.ic_reverse_order_white
        "RewindBlack" -> R.drawable.ic_rewind_black
        "RewindWhite" -> R.drawable.ic_rewind_white
        "RotateBlack" -> R.drawable.ic_rotate_black
        "RotateWhite" -> R.drawable.ic_rotate_white
        "SaveToAlbum" -> R.drawable.ic_save_to_album
        "SearchBlack" -> R.drawable.ic_search_black
        "SearchWhite" -> R.drawable.ic_search_white
        "SelectOFFBlack" -> R.drawable.ic_select_off_black
        "SelectOFFWhite" -> R.drawable.ic_select_off_white
        "SelectONBlack" -> R.drawable.ic_select_on_black
        "SelectONWhite" -> R.drawable.ic_select_on_white
        "SendBlack" -> R.drawable.ic_send_black
        "SendWhite" -> R.drawable.ic_send_white
        "SettingsBlack" -> R.drawable.ic_settings_black
        "SettingsWhite" -> R.drawable.ic_settings_white
        "ShuffleBlack" -> R.drawable.ic_shuffle_black
        "ShuffleWhite" -> R.drawable.ic_shuffle_white
        "Signal1Black" -> R.drawable.ic_signal1_bar_black
        "Signal1White" -> R.drawable.ic_signal1_bar_white
        "Signal2Black" -> R.drawable.ic_signal2_bars_black
        "Signal2White" -> R.drawable.ic_signal2_bars_white
        "Signal3Black" -> R.drawable.ic_signal3_bars_black
        "Signal3White" -> R.drawable.ic_signal3_bars_white
        "Signal4Black" -> R.drawable.ic_signal4_bars_black
        "Signal4White" -> R.drawable.ic_signal4_bars_white
        "SignalNoneBlack" -> R.drawable.ic_signal_none_black
        "SignalNoneWhite" -> R.drawable.ic_signal_none_white
        "SkipBackwardFifteenBlack" -> R.drawable.ic_skip_backward_fifteen_black
        "SkipBackwardFifteenWhite" -> R.drawable.ic_skip_backward_fifteen_white
        "SkipForwardFifteenBlack" -> R.drawable.ic_skip_forward_fifteen_black
        "SkipForwardFifteenWhite" -> R.drawable.ic_skip_forward_fifteen_white
        "Spacer" -> R.drawable.ic_spacer
        "SpeakerBlack" -> R.drawable.ic_speaker_black
        "SpeakerMuted" -> R.drawable.ic_speaker_muted
        "SpeakerOn" -> R.drawable.ic_speaker_on
        "SpeakerWhite" -> R.drawable.ic_speaker_white
        "StarBlack" -> R.drawable.ic_star_black
        "StarOutlineBlack" -> R.drawable.ic_star_outline_black
        "StarOutlineWhite" -> R.drawable.ic_star_outline_white
        "StarWhite" -> R.drawable.ic_star_white
        "StopBlack" -> R.drawable.ic_stop_black
        "StopWhite" -> R.drawable.ic_stop_white
        "TetheringBlack" -> R.drawable.ic_tethering_black
        "TetheringWhite" -> R.drawable.ic_tethering_white
        "ToggleOFFBlack" -> R.drawable.ic_toggle_off_black
        "ToggleOFFWhite" -> R.drawable.ic_toggle_off_white
        "ToggleONBlack" -> R.drawable.ic_toggle_on_black
        "ToggleONWhite" -> R.drawable.ic_toggle_on_white
        "Trash" -> R.drawable.ic_trash
        "UpBlack" -> R.drawable.ic_up_black
        "UpWhite" -> R.drawable.ic_up_white
        "VoiceMailBlack" -> R.drawable.ic_voice_mail_black
        "VoiceMailWhite" -> R.drawable.ic_voice_mail_white
        "VoiceMemoBlack" -> R.drawable.ic_voice_memo_black
        "VoiceMemoWhite" -> R.drawable.ic_voice_memo_white
        "WeeeMarkBlack" -> R.drawable.ic_weee_mark_black
        "WeeeMarkWhite" -> R.drawable.ic_weee_mark_white
        "WifiBlack" -> R.drawable.ic_wifi_black
        "WifiNoInternetBlack" -> R.drawable.ic_wifi_no_internet_black
        "WifiNoInternetWhite" -> R.drawable.ic_wifi_no_internet_white
        "WifiWhite" -> R.drawable.ic_wifi_white
        else -> null
    }
}
